---
title: "Homework 07"
author: "Shuai Ding"
date: "11/03/2019"
output:
  html_notebook:
    toc: yes
    toc_float: yes
    theme: spacelab
  html_document:
    toc: yes
    toc_float: yes
    theme:  spacelab
always_allow_html: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, cache=FALSE)
```

## 1. Define the base URL

```{r}
library(httr)
endpoint <- "https://data.lacity.org/resource/63jg-8b9z.csv"
```

## 2. Send a simple GET request
```{r}
get_result <- GET(endpoint)
get_result$status_code
str(get_result, max.level = 1)
```

## 3. Get the content of the response

The dataframe is 1000 observations of 28 variables.
```{r}
data <- content(get_result)
dim(data)
table(data$area_name)
```

## 4. Get your access token
```{r}
#R.home(component = "home")
#usethis::edit_r_environ()

query_params <- list("$limit" = "10000", "$$app_token" = Sys.getenv("LACRIME_APP_TOKEN"))
query_response <- GET('https://data.lacity.org/resource/63jg-8b9z.csv',query = query_params)
query_response$status_code

```

## 5. Limiting your query

I'm filtering the data set by looking at victim age of 19 in the Newton area.

```{r}
query_params_5 <- list("$limit" = "10000", "$$app_token" = Sys.getenv("LACRIME_APP_TOKEN"), "area_name" = "Newton","vict_age" = 19)
query_response_5 <- GET('https://data.lacity.org/resource/63jg-8b9z.csv',query = query_params_5)
query_response_5$status_code
```

## 6. Locations
```{r}
library(tidyverse)
df <- as.data.frame(content(query_response_5))
df1 <- df %>% select(lat, lon, area_name) 
df2 <- df1[1:50,]
df_finish = data.frame(lat=double(),
                 lon=double(), 
                 locationrevgeo=character(), 
                 stringsAsFactors=FALSE)
url <- "https://nominatim.openstreetmap.org/reverse"
for (i in 1:50){
  query_pa <- list("lat" =df2$lat[i],"lon"= df2$lon[i], "format" = "json", Sys.sleep(0.1))
  if (http_error(url)){
    warning("Failure")
  }else{
    content(query_pa)}
  loc_output <- GET(url, query = query_pa)
  loc_response <- content(loc_output)
  j_new = ""
  for (j in loc_response$address) {
    j_new = paste(j_new, j)
  }
  df_3 <- content(loc_output)
  df_3 <- data.frame(lat = df2$lat[i], lon = df2$lon[i],location = df2$area_name[i], locationrevgeo =  j_new)
  df_finish = rbind(df_finish, df_3)
}
df_finish
```














